adds data processing, not finished with Ray but will do that later

diff --git a/docker-compose-storage.yaml b/docker-compose-storage.yaml
--- a/docker-compose-storage.yaml
+++ b/docker-compose-storage.yaml
@@ -2,6 +2,8 @@ x-storage-common:
   &storage-common
     # there were permisisons issues due to mapped volume, so let's do this for prototyping
     user: "0:0"
+    env_file:
+      - .env
     networks:
       - helical-network
 
@@ -32,18 +34,20 @@ services:
   postgres:
     <<: *storage-common
 
-    image: postgres:15
+    image: postgres:16.4-bullseye
     container_name: storage-mlflow-postgres
     environment:
       POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
       POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
       POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
+      PGDATA: /var/lib/postgresql/data
+
     volumes:
       - ./data/mlflow-postgres/data/:/var/lib/postgresql/data
     ports:
       - "5432:5432"
     healthcheck:
-      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
+      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_POSTGRES_USER}"]
       interval: 5s
       timeout: 3s
       retries: 10
@@ -62,7 +66,10 @@ services:
           ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
         mc mb --ignore-existing myminio/${MLFLOW_S3_BUCKET:-mlflow} &&
         mc mb --ignore-existing myminio/${HELICAL_S3_BUCKET} &&
-        mc admin accesskey create myminio --access-key ${S3_ACCESS_KEY} --secret-key ${S3_SECRET_ACCESS_KEY}
+        if ! mc admin accesskey create myminio --access-key ${S3_ACCESS_KEY} --secret-key ${S3_SECRET_ACCESS_KEY}; then
+          echo "Failed to create access key (exit code $?), it already probably existed?"
+        fi
+        
       '
     restart: "no"
 
@@ -79,9 +86,9 @@ services:
       create-bucket:
         condition: service_completed_successfully
     environment:
-      POSTGRES_USER: ${POSTGRES_USER}
-      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
-      POSTGRES_DB: ${POSTGRES_DB}
+      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
+      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
+      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
       # Backend store URI built from vars
       MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
 
